insert into public.products (slug, name, description, category, price, image, images, features, specs, applications, active)
values
  ('cable-trays', 'Cable Trays & Ladders', 'High-performance cable management systems designed for safe, organized, and efficient routing in industrial and commercial environments.', 'Cable Management', 12000, '/images/cable-tray.png', array['/images/cable-tray.png', '/images/cable.jpg', '/images/cableladder.jpg']::text[], array['Pre-Galvanized & HDG Finishes', 'Complete Accessories System', 'Heavy-Duty Load Capacity', 'Corrosion Resistant Design']::text[], array['Material: Pre-Galvanized Steel / HDG', 'Widths: 100mm – 600mm', 'Load Capacity: up to 500kg/m']::text[], array['Industrial plants', 'Commercial buildings', 'Data centers and telecom rooms']::text[], true),
  ('cable-lugs', 'Cable Lugs', 'Durable and high-conductivity cable lugs engineered for secure electrical terminations and efficient power transmission.', 'Electrical Accessories', 450, '/images/cablelugs.jpeg', array['/images/cablelugs.jpeg', '/images/cable.jpg', '/images/cable-tray.png']::text[], array['Copper & Aluminum Types', 'High Conductivity', 'Corrosion Resistant Finish', 'Wide Size Range']::text[], array['Materials: Copper, Aluminum', 'Stud Sizes: M4 – M20', 'Plating: Tinned or Bare']::text[], array['Panel terminations', 'Transformer connections', 'Switchgear']::text[], true),
  ('circuit-breakers', 'Circuit Breakers', 'Advanced electrical protection devices designed to safeguard systems against overloads, short circuits, and faults.', 'Protection Devices', 8500, '/images/breakers.jpg', array['/images/breakers.jpg', '/images/product-protection.jpg', '/images/product-power.jpg']::text[], array['MCB / MCCB / RCD Types', '6A – 630A Ratings', 'Multi-Pole Configurations', 'High Breaking Capacity']::text[], array['Ratings: 6A – 630A', 'Poles: 1P – 4P', 'Standards: IEC/EN compliant']::text[], array['Distribution boards', 'Motor protection', 'Industrial panels']::text[], true),
  ('earth-rods', 'Earth Rods & Earthing Materials', 'Complete grounding materials including earth rods, clamps, and accessories for reliable electrical safety and protection.', 'Earthing & Protection', 2200, '/images/earthing-systems.jpg', array['/images/earthing-systems.jpg', '/images/inspection.png', '/images/product-installation.jpg']::text[], array['Copper & Galvanized Rods', 'High Conductivity', 'Complete Accessories', 'Long Service Life']::text[], array['Lengths: 1.2m, 1.8m, 3m', 'Materials: Galvanized steel, Copper bonded', 'Diameter: 16mm–25mm']::text[], array['Substations', 'Buildings', 'Telecom towers']::text[], true),
  ('conduits', 'Conduit Pipes & Fittings', 'Robust conduit systems designed to protect electrical wiring from mechanical damage and environmental conditions.', 'Wiring Systems', 650, '/images/conduit-pipe.jpg', array['/images/conduit-pipe.jpg', '/images/conduit-pipes-fittings.jpg', '/images/product-installation.jpg']::text[], array['Steel & PVC Options', 'Flexible & Rigid Types', 'Corrosion Resistant', 'Full Fittings Range']::text[], array['Materials: Steel, PVC', 'Diameters: 16mm–63mm', 'Standards: IP-rated options']::text[], array['Residential wiring', 'Industrial installations', 'Underground ducts']::text[], true),
  ('busbars', 'Tinned Copper Busbars', 'High-efficiency copper busbars with protective tin coating for reliable and low-loss power distribution.', 'Power Distribution', 18000, '/images/plated-copper-busbar.jpg', array['/images/plated-copper-busbar.jpg', '/images/product-power.jpg', '/images/wiring-device.png']::text[], array['High Conductivity Copper', 'Anti-Corrosion Coating', 'Custom Sizes Available', 'Low Power Loss']::text[], array['Widths: 20mm–100mm', 'Thicknesses: 3mm–10mm', 'Finish: Tinned copper']::text[], array['Switchgear', 'Distribution panels', 'Transformers']::text[], true),
  ('lightning-arrestors', 'Lightning Arrestors', 'Reliable surge and lightning protection systems designed to safeguard electrical installations and infrastructure.', 'Surge Protection', 5400, '/images/surge-arresters.png', array['/images/surge-arresters.png', '/images/product-protection.jpg', '/images/earthing-systems.jpg']::text[], array['High Surge Protection', 'IEC Compliant', 'Durable Construction', 'Easy Installation']::text[], array['Type: Surge arrestor, Neutral & Line configurations', 'Standards: IEC compliant', 'Mounting: Roof or tower mounts']::text[], array['Buildings', 'Towers', 'Substations']::text[], true),
  ('wiring-devices', 'Wiring Devices', 'Modern switches, sockets, and lighting solutions built for safety, durability, and aesthetic installations.', 'Wiring Systems', 1200, '/images/wiring-device.png', array['/images/wiring-device.png', '/images/electric.png', '/images/product-installation.jpg']::text[], array['Switches & Socket Outlets', 'LED Lighting Solutions', 'Weatherproof Options', 'Industrial Grade Designs']::text[], array['Finish: Matte, Gloss', 'Ingress Protection: IP44 options', 'Compatibility: Modular frames']::text[], array['Homes', 'Offices', 'Industrial sites']::text[], true),
  ('inspection-chambers', 'Inspection Chambers', 'Durable underground access systems designed for easy inspection and maintenance of cable and drainage networks.', 'Underground Infrastructure', 7600, '/images/inspection.png', array['/images/inspection.png', '/images/conduit-pipes-fittings.jpg', '/images/product-installation.jpg']::text[], array['Concrete / HDPE / Steel Options', 'Multiple Size Variants', 'High Strength Build', 'Corrosion Resistant']::text[], array['Materials: HDPE, Concrete, Steel', 'Diameters: 300mm–600mm', 'Load Class: Up to D400']::text[], array['Underground cabling', 'Drainage systems', 'Infrastructure maintenance']::text[], true),
  ('solar-materials', 'Solar Materials', 'Complete solar energy components including panels, lithium batteries, inverters, and accessories for reliable power solutions.', 'Renewable Energy', 45000, '/images/sola.jpg', array['/images/sola.jpg', '/images/product-renewable.jpg', '/images/product-backup.jpg']::text[], array['Solar Panels (300W – 700W)', 'Lithium & Deep Cycle Batteries', 'Hybrid & Off-Grid Inverters', 'Full Installation Accessories']::text[], array['Panels: 300W–700W', 'Batteries: 12V–48V systems', 'Inverters: 1kVA–10kVA']::text[], array['Residential solar', 'Commercial systems', 'Off-grid installations']::text[], true)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  category = excluded.category,
  price = excluded.price,
  image = excluded.image,
  images = excluded.images,
  features = excluded.features,
  specs = excluded.specs,
  applications = excluded.applications,
  active = excluded.active;
